// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jklxnevigyyjlprevfsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprbHhuZXZpZ3l5amxwcmV2ZnNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTU3MzQsImV4cCI6MjA2NjM3MTczNH0.ywcKus0VhlXMyDCz9Ng2Q5dhh1TdqiOfUSsQkk6XFNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);